name: "My action"
description: "My first action"

inputs: # Define los parámetros de entrada
  message: 
    description: "Message to display"
    required: true
    default: "Hello World"

runs:
  using: "composite"

  steps:
    - name: Hola Mundo
      shell: bash
      run: echo "${{ inputs.message }}"
    