name: Node.js CI

on: [push]

jobs:
  node-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.2.0
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install

    - name: Run tests
      id: test
      run: npm run test
    
    - name: deploy
      if: steps.test.outcome == 'success'
      run: echo "deploying"

    